name: Deploy MkDocs to GitHub Pages

# Ejecutar el workflow cuando haya un push en la rama master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    # Paso 1: Git clone del repositorio en la rama master
    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with:
    #     ref: master
    #     path: docs
    - name: Set up Git
        run: |
          git config --global user.name "Theasker"
          git config --global user.email "theasker@gmail.com"

      - name: Clone repository manually
        run: |
          mkdir -p docs  # Crea el directorio docs donde se hará el checkout
          git clone https://github.com/Theasker/pruebas.git temp-dir
          mv temp-dir/* docs/      # Mueve los archivos a la carpeta docs
          rm -rf temp-dir          # Elimina el directorio temporal
    
    # - name: Copy mkdocs.yml to root
    #   run: |
    #     mv docs/mkdocs.yml .  # Crea el directorio docs donde se hará el checkout
    #     date >> docs/README.md
    #     echo "\nHola mundo" >> docs/SUMMARY.md

    # # Paso 2: Instalar Python y MkDocs
    # - name: Set up Python and Install MkDocs
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x'
    # - run: |
    #     pip install mkdocs
    #     # pip install mkdocs-material  # Si usas el tema Material para MkDocs
    #     pip install mkdocs-windmill-dark

    # # Paso 3: Build la documentación con MkDocs
    # - name: Build the documentation
    #   run: |
    #     mkdocs build

    # # Paso 4: Desplegar en la rama gh-pages
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./site
