name: Deploy MkDocs to GitHub Pages

# Ejecutar el workflow cuando haya un push en la rama master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    # Paso 1: Git clone del repositorio en la rama master
    - name: Set up Git
      run: |
        git config --global user.name "Theasker"
        git config --global user.email "theasker@gmail.com"

    - name: Clone repository manually
      run: |
        git clone --branch master --single-branch https://github.com/${{ github.repository }} docs

        

    # Paso 2: Instalar Python y MkDocs
    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip tree
        pip3 install mkdocs
        # pip3 install mkdocs-material
        pip3 install mkdocs-windmill-dark

    # Paso 3: Build la documentación con MkDocs
    - name: Build the documentation
      run: |
        mv docs/mkdocs.yml .
        tree -L 2
        mkdocs build --site-dir ./site  # Genera los archivos del sitio en ./site
        tree -L 2                   # Lista los archivos generados en ./site
    
    # Paso 4: Copiar fichero a la rama gh-pages
    - name: Copy files to gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd docs
        git checkout gh-pages
        git rm -rf .
        git checkout master -- site
        mv site/* ./
        rmdir site
        git add .
        git commit -m "Copiado contenido de site desde master"
        git push origin gh-pages