name: Deploy MkDocs to GitHub Pages

# Ejecutar el workflow cuando haya un push en la rama master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio en la rama master
    - name: Checkout repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone https://github.com/${{ github.repository }} docs
        mv docs/mkdocs.yml .  # Mover el archivo mkdocs.yml a la raíz

    # Paso 1.2: Creación del fecha del deploy
    - name: Deploy date
      run: |
        echo "=> actualización de date"
        cd docs
        date > date.md
        git add date.md
        git commit -m "Actualización de la fecha"
        cd ..

    # Paso 2: Instalar Python y MkDocs
    - name: Set up Python and Install MkDocs
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip -y
        pip3 install mkdocs
        # pip3 install mkdocs-material  # Si usas el tema Material para MkDocs
        pip3 install mkdocs-windmill-dark

    # Paso 3: Build la documentación con MkDocs
    - name: Build markdown TOC
      run: |
        cd docs
        python createTOC.py
        cd ..

    # Paso 3: Build la documentación con MkDocs
    - name: Build the documentation
      run: |
        mkdocs build
        ls -la

    # Paso 4: Crear la rama gh-pages y copiar los archivos desde el directorio temporal
    - name: Deploy to GitHub Pages
      run: |
        echo "=> cd docs"
        cd docs

        echo "=> git clean -fd"
        git clean -fd

        echo "=> git checkout gh-pages"
        git checkout gh-pages

        echo "=> ls -la"
        ls -la

        echo "=> ls .."
        ls ..

        # echo "=> rm -rf *"
        # rm -rf *

        #echo "=> git checkout master -- site"
        #git checkout master -- site
        cp -r ../site/* .
        
        echo "=> git add ."
        git add .

        echo "=> git commit -m "Deploy MkDocs to GitHub Pages""
        git commit -m "Deploy MkDocs to GitHub Pages"

        echo "=> git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages"
        git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages